id: "schemas/delayer-api/schedule"
$schema: "http://json-schema.org/draft-06/schema#"
title: schedule
type: object
properties:
  schedule:
    type: object
    properties:
      pointInTime:
        $ref: "#/definitions/pointInTime"
    required:
      - pointInTime
    additionalProperties: false
  context:
    $ref: "#/definitions/context"
  action:
    type: object
    oneOf:
      -
        properties:
          type:
            enum:
              - http-request
          httpRequestConfig:
            $ref: "#/definitions/httpRequestConfig"
        additionalProperties: false
      -
        properties:
          type:
            enum:
              - sqs-send
          sqsSendConfig:
            $ref: "#/definitions/sqsSendConfig"
        additionalProperties: false
      -
        properties:
          type:
            enum:
              - custom
          customConfig:
            $ref: "#/definitions/customConfig"
        additionalProperties: false
required:
  - schedule
  - context
  - action
additionalProperties: false

definitions:
  pointInTime:
    type: string
    format: date-time
  context:
    type: object
    properties:
      headers:
        type: array
        items:
          type: object
      payload:
        type: string
    additionalProperties: true
  httpRequestConfig:
    type: object
    properties:
      method:
        $ref: "#/definitions/httpMethod"
      url:
        type: string
      requestType:
        enum:
          - WAIT_RETURN
          - FIRE_FORGET
    additionalProperties: false

  sqsSendConfig:
    type: object
    properties:
      queueName:
        type: string
      messageAttributes:
        type: array
        items:
          type: object
      payload:
        type: string
    additionalProperties: false

  customConfig:
    type: object
    properties:
      configName:
        type: string
      topicArn:
        type: string
    required:
      - configName
    additionalProperties: true

  httpMethod:
    enum:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      - HEAD
      - OPTIONS

