id: "schemas/delayer-api/schedule"
$schema: "http://json-schema.org/draft-06/schema#"
title: schedule
type: object
properties:
  schedule:
    type: object
    properties:
      pointInTime:
        $ref: "#/definitions/pointInTime"
    required:
      - pointInTime
    additionalProperties: false
  context:
    $ref: "#/definitions/context"
  action:
    type: object
    properties:
      type:
        enum:
          - HTTP
          - SQS_SEND
          - SQS_RECEIVE
          - SNS_SEND
      httpConfig:
        $ref: "#/definitions/httpConfig"
    additionalProperties: false
  notification:
    type: object
    properties:
      slack:
        $ref: "#/definitions/slackNotification"
      email:
        $ref: "#/definitions/emailNotification"
    anyOf:
      - required:
        - slack
      - required:
        - email
required:
  - schedule
  - context
  - action
additionalProperties: false

definitions:
  pointInTime:
    type: string
    format: date-time
  context:
    type: object
    properties:
      headers:
        type: array
        items:
          type: object
      payload:
        type: string
    additionalProperties: false
  httpConfig:
    type: object
    properties:
      method:
        $ref: "#/definitions/httpMethod"
      url:
        type: string
      requestType:
        enum:
          - WAIT_RETURN
          - FIRE_FORGET
      returnExpected:
        type: object
        properties:
          code:
            type: array
            items:
              type: number
          body:
            type: string
        required:
          - code
      preCheck:
        type: object
        properties:
          method:
            $ref: "#/definitions/httpMethod"
          url:
            type: string
    additionalProperties: false

  httpMethod:
    enum:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      - HEAD
      - OPTIONS

