AWSTemplateFormatVersion: "2010-09-09"

Resources:
  ScheduleCreatedEvent:
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: "DELAYER_EVENT_schedule-created"
      DisplayName: Schedule registration event topic
  ScheduleCancelledEvent:
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: "DELAYER_EVENT_schedule-cancelled"
      DisplayName: Cancel schedule event topic
  ScheduleInWaitQueueEvent:
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: "DELAYER_EVENT_schedule-waiting"
      DisplayName: Schedule sent to DELAYER_wait-queue
  ActionFinishedEvent:
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: "DELAYER_EVENT_action-finished"
      DisplayName: Action Finalized event

  HTTPAction:
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: "DELAYER_ACTION_HTTP"
      DisplayName: HTTP Action executor topic
  SQSSendAction:
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: "DELAYER_ACTION_SQS_SEND"
      DisplayName: SQS Message Post Action executor topic
